### ISSUE TITLE
Cannot install font components

### ISSUE THREAD

**Issue by pcfountain** [jsmarcus/Iconize#1]
I working on Visual Studio 2015, Update 3.  I create a basic app using the Xamarin.Forms XAML template.  Then in the PCL project, using NuGet, I add a reference to FormsPlugin.Iconize.  This works fine.  But when I try to add a reference to any of the font libraries, such as Iconize.FontAwesome, I get the message shown below.  I have tried this with all the fonts, and I get the same message.

===============================
Could not install package 'Xam.Plugin.Iconize.FontAwesome 1.5.0.2-beta'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by jsmarcus** [comment]
The fonts only get installed in the platform projects (Android and iOS)

**Comment by pcfountain** [comment]
OK, thank you for the tip.  I was able to get everything working after looking at your sample projects.

**Comment by dagostinelli** [comment]
@jsmarcus The readme on the project's homepage talks about putting code into the App constructor in the PCL.  I found that confusing since the fonts only get installed in the platform projects.  Is there some other way to do this?
