### ISSUE TITLE
iOS: IconLabel not rendering icon if FontSize set dynamically

### ISSUE THREAD

**Issue by hardcodet** [jsmarcus/Iconize#10]
I ran into a super weird issue here. Look at the two labels below:

        <Grid x:Name="LayoutRoot">
            
            <iconize:IconLabel TextColor="{Binding CircleColor}"
                               FontSize="{Binding ButtonSize, Converter={StaticResource CircleButtonSizeConverter}}"
                               Text="fa-circle"
                               HorizontalTextAlignment="Center"
                               VerticalTextAlignment="Center" />
            
            
            <iconize:IconLabel TextColor="White"
                               FontSize="{Binding ButtonSize, Converter={StaticResource CircleButtonIconSizeConverter}}"
                               Text="fa-facebook"
                               HorizontalOptions="Center"
                               VerticalOptions="Center"
                               HorizontalTextAlignment="Center"
                               VerticalTextAlignment="Center" />
        </Grid>

The first of those labels renders the icon correctly. The seconds doesn't, but shows the text of the assigned icon instead ("fa-facebook").

I think the main bug here is that the FontSize is being set dynamically, which resets the font lookup. If I set it to a fixed value (e.g. 32), Both icons render fine.

This of course left me with a bit of a WTF as to why one worked and one didn't. After trimming the fat of the control, I was left with the above two labels that have one major difference: One has the TextColor assigned through a binding (which causes the icon to render), one has a hardcoded TextColor, which causes the Label to screw up. Again, those are probably just follow-up issues of the FontSize bug.

This is XF 2.3.3 pre1 on iOS with Iconize 1.0.1.0

Thanks,
Philipp

**Comment by hardcodet** [comment]
Some further observations (still iOS only)

On another page, the control renders both the circle and the icon, but not the bound color. I really appears that the label resets itself on property changes.

**Comment by hardcodet** [comment]
Ok, I fixed this for my project with a minimal custom renderer that doesn't extend LabelRenderer. This comes with way less overhead anyway.

In case anybody wants to use it (or you want to replace the current renderer): Note that I was too lazy to check for the text alignment property and just hardcoded it since I'm centering layouts anyway.

In my PCL project:

    public class XIconLabel : Label
    {
    }


In my iOS project:

    public class IconLabelRenderer : ViewRenderer<XIconLabel, UILabel>  
    {
        /// <summary>
        /// Raises the <see cref="E:ElementChanged" /> event.
        /// </summary>
        /// <param name="e">
        /// The <see cref="ElementChangedEventArgs{Label}" /> instance containing the event data.
        /// </param>
        protected override void OnElementChanged(ElementChangedEventArgs<XIconLabel> e)
        {
            if (e.NewElement != null)
            {
                if (this.Control == null)
                {
                    UILabel uiview = new UILabel(CGRect.Empty);
                    UIColor clear = UIColor.Clear;
                    uiview.BackgroundColor = clear;
                    uiview.TextAlignment = UITextAlignment.Center;
                    this.SetNativeControl(uiview);
                }
                this.UpdateText();
            }
            base.OnElementChanged(e);
        }

        /// <summary>
        /// Called when [element property changed].
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="e">
        /// The <see cref="PropertyChangedEventArgs" /> instance containing the event data.
        /// </param>
        protected override void OnElementPropertyChanged(Object sender, PropertyChangedEventArgs e)
        {
            base.OnElementPropertyChanged(sender, e);

            switch (e.PropertyName)
            {
                case nameof(IconLabel.FontSize):
                case nameof(IconLabel.Text):
                case nameof(IconLabel.TextColor):
                    UpdateText();
                    break;
            }
        }


        /// <summary>
        /// Updates the text.
        /// </summary>
        private void UpdateText()
        {
            XIconLabel label = Element;
            IIcon icon = Iconize.FindIconForKey(label.Text);
            if (icon != null)
            {
                //associated font
                IIconModule iconModule = Iconize.FindModuleOf(icon);
                UIFont font = iconModule?.ToUIFont((nfloat)Element.FontSize);

                //assign the unicode character
                if (font != null)
                {
                    Control.Text = $"{icon.Character}";
                    Control.Font = font;
                    Control.TextColor = label.TextColor.ToUIColor();
                }
            }
        }
    }

**Comment by jsmarcus** [comment]
I believe this is resolved with the current 2.0.0 beta on nuget. I chose to base the renderers on the ones in Xamarin.Forms so that they got support for things like text alignment out of the box and any future enhancements. I'm glad you were able to solve it for your project though.
