### ISSUE TITLE
IOS icontoolbar doesn't show question marks with version 3.3.093 and .NetStandard.Library

### ISSUE THREAD

**Issue by Pirate911** [jsmarcus/Iconize#107]
Hi , I am having issues using iconize like below , it shows question mark . I tried most of the icons names as in fa icon sheet but non of them worked for me . 
i'm very sure setup of files and naming convention is followed . 

I am using NetStandard.Library 2.0 for IOS 

<iconize:IconToolbarItem Priority="0" Order="Primary"  Icon="fab-500px" Clicked="OnAddItem_Click" />

anyone got it working plz send me working sample please .

thank you so  much guys.

**Comment by jsmarcus** [comment]
Are you using an IconNavigationPage in place of the standard NavigationPage?

**Comment by Pirate911** [comment]
Yes but it's ok now . It's resolved right after I updated the nuget to 3.4.0 . 

Thank you so much Jeremy
