### ISSUE TITLE
Net Standart 2 - not show icons!

### ISSUE THREAD

**Issue by decv86** [jsmarcus/Iconize#108]
The plugin does not work - as soon as I did not try, did anyone come across it? help me please!
![2018-11-14_23-57-55](https://user-images.githubusercontent.com/22221485/48512064-97c0b880-e869-11e8-9503-bd5775b68f75.png)

**Comment by jsmarcus** [comment]
I have updated the sample project to show it working properly.

![annotation 2018-11-16 161309](https://user-images.githubusercontent.com/1919776/48647631-81764200-e9ba-11e8-8af3-6492dbdfef0c.jpg)

**Comment by Pirate911** [comment]
thank you so much for your response and your all effort .
