### ISSUE TITLE
How to use IconizeExtensions in xaml

### ISSUE THREAD

**Issue by Jasuchin** [jsmarcus/Iconize#109]
`<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:controls="clr-namespace:KloudHotelsPlus.Controls"
             xmlns:local="clr-namespace:KloudHotelsPlus.Views"
             xmlns:ffimageloadingsvg="clr-namespace:FFImageLoading.Svg.Forms;assembly=FFImageLoading.Svg.Forms"
             xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
             xmlns:iconize="clr-namespace:Plugin.Iconize;assembly=Plugin.Iconize"
             x:Class="KloudHotelsPlus.Views.ActiveFolioPage"
             x:Name="Test"
             Title="Test"
             iconize:IconizeExtensions.ToolbarItems="md-history">`

> Value cannot be null.
> Parameter name: key

Can I use  _iconize:IconizeExtensions.ToolbarItems="md-history"_ like this?

**Comment by jsmarcus** [comment]
No, it doesn't work that way.
