### ISSUE TITLE
Add new icons 

### ISSUE THREAD

**Issue by Pirate911** [jsmarcus/Iconize#111]
Hi @jsmarcus  , Do you have any plans to add these fonts to Iconize lib ? 

https://feathericons.com/
https://jam-icons.com/

Thanks

**Comment by jsmarcus** [comment]
Feather is svg only so it doesn't work with this project. Jam could be added fairly easily as it provides a font file.

**Comment by Pirate911** [comment]
I understand about feathericon but can I just add it like fontawesome font files or we need have new nuget package for this font ?

**Comment by jsmarcus** [comment]
You can always create your own library following the other font projects but I have just published Jam icons to nuget.
