### ISSUE TITLE
Icons not showing in iOS12

### ISSUE THREAD

**Issue by decv86** [jsmarcus/Iconize#113]
Hi!
Icons not showing in iOS12! In iOS 10 - work.
Is there a solution? Thank.

**Comment by Scottyaim** [comment]
Any news on this? Did you solve it @decv86 ?
Icons are not showing on IOS 12 for me either

**Comment by Scottyaim** [comment]
Solved got the answer at https://github.com/jsmarcus/Iconize/issues/75#issuecomment-436632700

**Comment by decv86** [comment]
@Scottyaim Hi, yes, its solution.
