### ISSUE TITLE
Possible bug with prism

### ISSUE THREAD

**Issue by angelru** [jsmarcus/Iconize#119]
Hello,

When navigate prism framework a contentpage that have icons with MVVM binding, when going back

jump the exception:

```
12-28 22:24:08.375 I/MonoDroid(29558): UNHANDLED EXCEPTION:
12-28 22:24:08.379 I/MonoDroid(29558): System.ArgumentNullException: Value cannot be null.
12-28 22:24:08.379 I/MonoDroid(29558): Parameter name: iconKey
12-28 22:24:08.380 I/MonoDroid(29558):   at Plugin.Iconize.Iconize.FindIconForKey (System.String iconKey) [0x00015] in C:\projects\iconize\src\Plugin.Iconize\Iconize.cs:129 
12-28 22:24:08.380 I/MonoDroid(29558):   at Plugin.Iconize.IconLabelRenderer.UpdateText () [0x0001f] in C:\projects\iconize\src\Plugin.Iconize\Platform\Android\Renderers\IconLabelRenderer.cs:126 
12-28 22:24:08.380 I/MonoDroid(29558):   at Plugin.Iconize.IconLabelRenderer.OnTextChanged (System.Object sender, Android.Text.TextChangedEventArgs e) [0x00000] in C:\projects\iconize\src\Plugin.Iconize\Platform\Android\Renderers\IconLabelRenderer.cs:105 
12-28 22:24:08.380 I/MonoDroid(29558):   at (wrapper delegate-invoke) System.EventHandler`1[Android.Text.TextChangedEventArgs].invoke_void_object_TEventArgs(object,Android.Text.TextChangedEventArgs)
```

**Comment by angelru** [comment]
Someone with the same issue?

**Comment by adamsapple** [comment]
I heve same plobrem. X(

**Comment by EndlessDelirium** [comment]
If data binding is used it is common that the property is null at first. With older versions this wasn't an issue but a recent commit changes the behavior and an exception is thrown for such scenarios:
This commit breaks things: https://github.com/jsmarcus/Iconize/commit/6638c6735fca0d79c3a25bb465ab1297872ec94e#diff-913f8d5c561cd24bc687f40058980ae2
This also breaks things on my side. What I did was rolling back to version 3.4.0.100 that doesn't yet contain this change.

Obviously it would be nice to know about invalid icon identifiers. To just throw an exception in there however can't be the solution.

**Comment by adamsapple** [comment]
@EndlessDelirium i m trying your recommended version 3.4.0.100.
it looks like good.
thank you!! :D
