### ISSUE TITLE
Could not load image named: {0} - Android icons not loading

### ISSUE THREAD

**Issue by Wazzo79** [jsmarcus/Iconize#125]
I followed the instructions from @DawidBester in #68, however I still cannot get the images to load on Android.

I am currently running 3.4.0.110 for both Xam.Plugin.Iconize & Xam.Plugin.Iconize.FontAwesome.

App.xaml.cs

        public App()
        {
            InitializeComponent();

            Iconize
                .With(new Plugin.Iconize.Fonts.FontAwesomeRegularModule())
                .With(new Plugin.Iconize.Fonts.FontAwesomeSolidModule());

            MainPage = new Home();
        }

MainActivity.cs

        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);

            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            Plugin.Iconize.Iconize.Init(Resource.Id.toolbar, Resource.Id.sliding_tabs);

            LoadApplication(new App());
        }

I have also added the fonts to the Assets folder and have set the Build Action to _AndroidAsset_.

<img width="280" alt="screenshot 2019-02-03 at 15 30 33" src="https://user-images.githubusercontent.com/12134495/52177436-5933fd80-27c9-11e9-8605-e5a718de1dd7.png">

I have confirmed that the fonts are available at runtime by setting a breakpoint as below:

<img width="855" alt="screenshot 2019-02-03 at 15 39 49" src="https://user-images.githubusercontent.com/12134495/52177482-0eff4c00-27ca-11e9-8a87-f32501e16c37.png">

However, when I run my app on a physical device I get the following:

<img width="570" alt="screenshot 2019-02-03 at 15 42 10" src="https://user-images.githubusercontent.com/12134495/52177509-669db780-27ca-11e9-91f8-cdc4eba60e79.png">

I am setting the _Icon_ property values through XAML, but I am loading the IconTabbedPage inside an IconNavigationPage. This works as expected on iOS...what am I doing wrong?

**Comment by jsmarcus** [comment]
The instructions in that comment are mostly correct. We are using the ttf files however and not the otf. You can grab a copy of the font files here: https://github.com/jsmarcus/Iconize/tree/master/src/Fonts/Plugin.Iconize.FontAwesome

**Comment by Wazzo79** [comment]
Thanks @jsmarcus for your swift reply. 

I did as you suggested and replaced the .otf files with .ttf files:
<img width="297" alt="screenshot 2019-02-03 at 19 28 43" src="https://user-images.githubusercontent.com/12134495/52181096-d3c74200-27f6-11e9-9bb4-d98380290cd1.png">

I still cannot see any icons and I am still getting the following errors in my output:

<img width="570" alt="screenshot 2019-02-03 at 15 42 10" src="https://user-images.githubusercontent.com/12134495/52181114-0a9d5800-27f7-11e9-85b3-60c263ae6ab4.png">
 
Are you able to replicate what I am getting in your Android environment?

**Comment by Wazzo79** [comment]
Any ideas?

**Comment by Wazzo79** [comment]
@jsmarcus , may I suggest that you load an updated sample of an application since the XF 3 update? There have been a number of questions surrounding exactly how the font files are added to each of the platform projects, and I feel that an updated sample would assist the community greatly. (If I had mine working I would submit a PR).

**Comment by Wazzo79** [comment]
@jsmarcus , apologies, I see you updated the samples 5 days ago. I have resolved this issue by completely rebuilding my XF projects. No need to manually add fonts either.
