### ISSUE TITLE
IconDrawable not found

### ISSUE THREAD

**Issue by venixsoftwaregeneral** [jsmarcus/Iconize#129]
Hi, in a Xamarin project I used IconDrawable in the Android project since 2018.
After updated NuGet Plugin.Iconize to last version 3.5.0.117, I can't use IconDrawable and can't compile anymore the Droid project.

Where am I wrong?
My using:
`using Plugin.Iconize;`

And my call
`IconDrawable pinFrame;`
`pinFrame = new IconDrawable(Context, App.DEVICE_PIN_FRAME);`
`pinFrame.SizePx(pinFrameHeight);`

`Error CS0246: The type or namespace name 'IconDrawable' could not be found (are you missing a using directive or an assembly reference?) (CS0246)`

**Comment by jsmarcus** [comment]
This library only targets Xamarin.Forms projects now. I am sorry for the loss of functionality for you.
