### ISSUE TITLE
Support IconToolbarItem on UWP

### ISSUE THREAD

**Issue by YZahringer** [jsmarcus/Iconize#13]
IconToolbarItem does not work with Xamarin.Forms on UWP

**Comment by jsmarcus** [comment]
Can you please try with 2.0.0 beta on nuget?

**Comment by jsmarcus** [comment]
p.s. - There are breaking changes with this build. Everything has been simplified by making it only support Xamarin.Forms. All the modules can (and should) be installed in all projects (even the icons). The FormsPlugin project/module has been deprecated and the number of libraries required has been cut in half or in third depending.

**Comment by YZahringer** [comment]
The icon is still not displayed in my UWP project. I try with Material Design icons.
`<ContentPage.ToolbarItems>
    <iconize:IconToolbarItem Icon="md-close" />
</ContentPage.ToolbarItems>`

**Comment by jsmarcus** [comment]
Do you have your ContentPage wrapped in an IconNavigationPage?

**Comment by YZahringer** [comment]
Sorry, yes it works with IconNavigationPage.

But I can not execute my CustomRenderer:
```cs
[assembly: Xamarin.Forms.Platform.UWP.ExportRenderer(typeof(Plugin.Iconize.IconNavigationPage), typeof(App.UWP.Renderers.CustomIconNavigationPageRenderer))]
namespace App.UWP.Renderers
{
    using System;

    public class CustomIconNavigationPageRenderer : Plugin.Iconize.IconNavigationPageRenderer
    {
        public CustomIconNavigationPageRenderer()
        {
            throw new Exception();
        }
    }
}
```
The constructor is never called.

**Comment by jsmarcus** [comment]
In order to have your own custom renderer you have to have your own custom control.

```
public class CustomIconNavigationPage : Plugin.Iconize.IconNavigationPage
{
}
[assembly: Xamarin.Forms.Platform.UWP.ExportRenderer(typeof(CustomIconNavigationPage), typeof(App.UWP.Renderers.CustomIconNavigationPageRenderer))]
public class CustomIconNavigationPageRenderer : Plugin.Iconize.IconNavigationPageRenderer
{
}
```
