### ISSUE TITLE
Do this plugin is necessary yet?

### ISSUE THREAD

**Issue by candidodmv** [jsmarcus/Iconize#135]
At release v3.6 of Xamarin.Forms was implemented the feature FontIconSource as described on this [issue](https://github.com/xamarin/Xamarin.Forms/issues/3189) , so what this plugin does beyond that build in feature?

**Comment by jsmarcus** [comment]
FontImageSource is nice and will allow us to obsolete some of the code but it doesn't make this project unnecessary. For one, it will only work for images which are memory intensive (vs a label or button using just text). Also, most places only support FileImageSource right now so you won't be able to use FontImageSource in places like the Toolbar yet. I believe they are trying to change all those specific FileImageSources to just ImageSource. However, once that is done you would still have to know all the specific Unicode values and the font names, etc. We have an IconFontImageSource available shortly that won't require you to know the font names or Unicode. You'll be able to continue using the ligatures like fa-rabbit and have it work with the new goodness.
