### ISSUE TITLE
WeatherIcons: CoreText performance note on IOS

### ISSUE THREAD

**Issue by MrBasque** [jsmarcus/Iconize#16]
When using the "Plugin.Iconize.WeatherIcons.iOS" package, the following warning is displayed at runtime:

	 * 	CoreText performance note: Client called CTFontCreateWithName() using name "Weather Icons" and got font with PostScript name "WeatherIcons-Regular". For best performance, only use PostScript names when calling this API.

Remark: This could be fixed by specifying the correct Font-name "`WeatherIcons-Regular`" in the constructor:

```
public WeatherIconsModule() : base("Weather Icons", "WeatherIcons-Regular", "iconize-weathericons.ttf", WeatherIconsCollection.Icons)
    {
        // Intentionally left blank
    }
```

**Comment by jsmarcus** [comment]
Fixed in commit 13073c3. Thank you.
