### ISSUE TITLE
Problems creating an IconNavigationPage with an icon

### ISSUE THREAD

**Issue by AndreasReitberger** [jsmarcus/Iconize#170]
Hi,
I'm trying to add an icon to my `IconNavigationPage` in XAML.

`<iconize:IconTabbedPage.Children>
<iconize:IconNavigationPage Title="Settings" Icon="mdi-cogs">
            <x:Arguments>
                <views:SettingsPage/>
            </x:Arguments>
        </iconize:IconNavigationPage>
</iconize:IconTabbedPage.Children>
`

While the icon is shown fine in the `IconToolbarItem`, it seems not to work with the `IconNavigationPage`. Or do I miss something?

`<iconize:IconToolbarItem Command="{Binding ModalTestCommand}" Icon="mdi-cogs" />`

**Comment by melanie-glanum** [comment]
Hi,
Same problem here... Did you have any news @AndreasReitberger?
