### ISSUE TITLE
Sample doesn't work on iOS

### ISSUE THREAD

**Issue by Goldstrike** [jsmarcus/Iconize#33]
Hello,

I've downloaded the sources from [jsmarcus/Iconize](https://github.com/jsmarcus/Iconize) and I've built the samples.

But I encounter a problem on iOS: the fonts don't seem to work.
[Screenshot iOS](https://img11.hostingpics.net/pics/453870IconizesampleiOS.png)

On Android, there is no problem:
[Screenshot Android](https://img11.hostingpics.net/pics/871867IconizesampleAndroid.png)

**_I've also seen that only the the PCL project seems to contain NuGets packages: how is it possible?_**

**Comment by Goldstrike** [comment]
After having reopened the solution, this works well. I think that's because I've edited the `info.plist` outside of Visual Studio: so the change wasn't probably taken into account.

**Comment by beko1997** [comment]
This could be related to #27, which is now merged but not yet released in a version. 

In the meantime you can try adding the fonts (.ttf files) to the iOS project inside the `/Resources` folder and add this inside the Info.plist file (inside the `dict` element):

**Info.plist (iOS)**
````xml
  <key>UIAppFonts</key>
  <array>
    <string>iconize-fontawesome.ttf</string>
    <string>iconize-material.ttf</string>
  </array>
````

**Comment by Goldstrike** [comment]
Iit seems to work like that, thank you!
