### ISSUE TITLE
PCL Setup

### ISSUE THREAD

**Issue by danielc103** [jsmarcus/Iconize#36]
Can't install Fonts on PCL, targeting wrong version. 

#1 implies that I only need to install fonts in Droid/iOS projects. 

PCL instructions implies that Fonts need to be installed on PCL and initialized using 
```
With(new Iconize.Fonts.FontAwesome())
```
There's also an additional package available, ```Xam.FormsPlugin.Iconize``` linked back to this repo.   

Question - how to properly setup for PCL use?  Sorry if I missed something.

**Comment by karnash** [comment]
same problem......... Fonts..  not in the namespace.... :(

**Comment by beko1997** [comment]
Below is my current set-up which seems to work:

NuGet installed (In PCL, Android and iOS):
- Xam.Plugin.Iconize
- Xam.Plugin.Iconize.FontAwesome

Please do not use `Xam.FormsPlugin.Iconize`, it seems to be a previous version of this package which is still available.

**View.xaml**
````xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage x:Name="Page"
             xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:iconize="clr-namespace:Plugin.Iconize;assembly=Plugin.Iconize">
        <iconize:IconLabel Text="fa-clock-o"></iconize:IconLabel>
</ContentPage>
````

**App.xaml.cs (PCL)**
````cs
        public App()
        {
            InitializeComponent();
            Iconize
                          .With(new Plugin.Iconize.Fonts.FontAwesomeModule())
                          .With(new Plugin.Iconize.Fonts.MaterialModule());

            MainPage = new NavigationPage(new View());
        }
````

**Info.plist (iOS)**
````xml
  <key>UIAppFonts</key>
  <array>
    <string>iconize-fontawesome.ttf</string>
    <string>iconize-material.ttf</string>
  </array>
````
Insert this inside the `<dict>` element. You can specify multiple .ttf files, please add the files to the iOS project `/Resources` folder.
