### ISSUE TITLE
IconToolbarItem only support AppCompat project,please indicate it in Readme

### ISSUE THREAD

**Issue by yz1311** [jsmarcus/Iconize#4]
IconToolbarItem only support AppCompat project,please indicate it in Readme.
Need to replace NavigationPage with IconNavigationPage,or nothing will appear.
I ran into it and read the source code to figure it out.

**Comment by jsmarcus** [comment]
The readme has been updated to mention AppCompat in all places where Android is mentioned. It has also been updated to say that IconNavigationPage is required for IconToolbarItem.
