### ISSUE TITLE
Namespacename "Droid" could not be found within namespace "Plugin.Iconize"

### ISSUE THREAD

**Issue by tschennie** [jsmarcus/Iconize#44]
I installed version  2.0.0.37-beta of Xam.Plugin.Iconize and Xam.Plugin.Iconize.Material, which is compatible to ".NETPortable,Version=v4.5,Profile=Profile111".

With initalizing within the Xamarin.Android project by
_Plugin.Iconize.Droid.IconControls.Init(Resource.Id.toolbar, Resource.Id.tabs);_
I get the error that the namespace name "Droid" could not be found within namespace "Plugin.Iconize".
And also "Resource.Id.tabs" doesn't exists..

What am I doing wrong?

**Comment by jsmarcus** [comment]
Use the following:
```c#
Plugin.Iconize.Iconize.Init(Resource.Id.toolbar, Resource.Id.tabs);
```
