### ISSUE TITLE
Does Iconize support NetStandard?

### ISSUE THREAD

**Issue by satputerohan** [jsmarcus/Iconize#46]
Hi,
I am using current stable 1.0.10 since months. I wanted to upgrade my project to NetStandard. Does Iconize support NetStandard?

**Comment by karlingen** [comment]
@jsmarcus Do you happen to know if anyone started on this or should I make an attempt?

**Comment by Pirate911** [comment]
I don't think it's supported yet .

**Comment by jsmarcus** [comment]
Netstandard has been supported for about a year.

**Comment by Pirate911** [comment]
> Netstandard has been supported for about a year.

Thanks for the reply @jsmarcus  but the sample posted isn't working , plz check this #108 .

**Comment by jsmarcus** [comment]
Look at the sample again. I have updated it to show it working.

**Comment by CZEMacLeod** [comment]
@jsmarcus It looks like that requires 3.4.0.100 but the latest published (on nuget.org at least) is 3.3.0.93
