### ISSUE TITLE
How can I get the version with FontAwesome 4.7.0?

### ISSUE THREAD

**Issue by gercobrandwijk** [jsmarcus/Iconize#5]
In commit history I found that FontAweSome was updated to 4.7.0 on Nov 2: https://github.com/jsmarcus/Iconize/commit/e89000ee79d39b0a4fee25b1c600ccd07d7b2b48

How can I use this already? I have installed the latest prelease (1.5.0.8-beta) in my projects, but still the old FontAwesome 4.6.3 is in there...

**Comment by jsmarcus** [comment]
It should be available in the prerelease. I will take a look and see why it hasn't updated.

**Comment by gercobrandwijk** [comment]
Did you already have a change to look at it?

**Comment by hardcodet** [comment]
I just ran into the same issue. `FontAwesomeCollection `contains the new 4.7 keys - is it still the old font by any chance?

**Comment by jsmarcus** [comment]
I updated the font file but for whatever reason it doesn't appear to be in the compiled project.

**Comment by juanc5ibanez** [comment]
Hi everyone. I had the same issue. I was able to get it to work by downgrading the mono android version from 7 to 6. and then directly referenced the Plugin.Iconize.FontAwesome.Droid dll from my droid project. Hope this helps in the meanwhile.

**Comment by malzeer** [comment]
Any update on this issue ?

**Comment by jsmarcus** [comment]
The latest FontAwesome is available through the 2.0.0 beta on nuget. I hope to have it released as stable in the coming days. Please take a look.

**Comment by jsmarcus** [comment]
p.s. - There are breaking changes with this build. Everything has been simplified by making it only support Xamarin.Forms. All the modules can (and should) be installed in all projects (even the icons). The FormsPlugin project/module has been deprecated and the number of libraries required has been cut in half or in third depending.
