### ISSUE TITLE
Iconize not .NET Standard 2.0 ready? 

### ISSUE THREAD

**Issue by xpacheco** [jsmarcus/Iconize#59]
It appears that Iconize is not compatible with .NET Standard 2.0.  I have not been able to include the Xam... assemblies without errors. 

I've have been able to add the Xam assemblies to my .net standard 2.0 solution by downgrade Xamarin Forms to 2.4.0.91020.  It still does not work, however; the icons do not display. 

Please inform when Iconize will be compatible with the latest Xamarin forms and .NET Standard 2.0.

**Comment by tmt242001** [comment]
"2.0.0.37-beta" works with .NET Standard 2.0

**Comment by kolchy** [comment]
Refer the issue #37 - from what I've discovered, don't use the Xam.FormsPlugin.Iconize pkg. It's working OK for me with just the Xam.Plugin.Iconize + the relevant font pkg.

**Comment by xpacheco** [comment]
Can't seem to get this working. This is what I have.  Three projects in my solution: 

FAApp solution (this is the .net standard shared project)
FAApp.Android (this is the android app)
FAApp.iOS (the iOS App)

I've added the following packages: 

Xam.Plugin.Iconize 1.5.0.13-beta (added to all three projects)
Xam.FormsPlugin.Iconize 2.0.0.37-beta  (added to all three projects)
Xam.Plugin.Iconize.FontAwesome 2.0.0.37-beta (added to all three projects)

When I try to build my solution, I get the following error.  Any ideas? 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Plugin.Iconize.Droid, Version=1.5.0.13, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Plugin.Iconize.Droid.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	FAApp.Android

**Comment by xpacheco** [comment]
Ok, @kolchy , I've removed Xam.FormsPlugin.Iconize, however the line: 

           Plugin.Iconize.Droid.IconControls.Init(Resource.Id.toolbar, Resource.Id.tabs);

Cannot resolve "Plugin.Icons" or "Resource.Id.Tabs" preventing compilation.  Even though the package is included it doesn't seem to realize the namespace for the Xam packages.  Still working on it. :) Any ideas?

**Comment by kolchy** [comment]
Hey @xpacheco here is what I have:

`Plugin.Iconize.Iconize.Init(Resource.Id.toolbar, Resource.Id.sliding_tabs);`

**Comment by xpacheco** [comment]
@kolchy , that worked! Thanks!

**Comment by cklenk** [comment]
Did anyone else have this error: System.MissingMethodException: void Plugin.Iconize.Iconize.Init(int,int)? I followed the above steps exactly. Do you think it's just a vs/xamarin cache issue?
