### ISSUE TITLE
Code behind Icon

### ISSUE THREAD

**Issue by HectorMeneses333** [jsmarcus/Iconize#6]
Hi,
Is it possible to create an Icon on c# side vs XAML?

Thanks!!
Hector

PS. Great job creating this Plugin! thanks!

**Comment by cklenk** [comment]
I wonder if it has something to do with a newer version of Xamarin.Forms. I recently updated to 2.3.3.175 and it is no longer working.

**Comment by cklenk** [comment]
Oh oops, I figured out you actually have to add the Xam.FormsPlugin.Iconize to each of your projects if you are creating a Icon from c#.

**Comment by jsmarcus** [comment]
Yes, you can create any of the Icon controls in code.
