### ISSUE TITLE
Updated NuGet Package

### ISSUE THREAD

**Issue by blimkemann** [jsmarcus/Iconize#65]
Can we PLEASE get an updated version in NuGet? It's been 6 months and you've made quite a few improvements and fixes!

**Comment by Goldstrike** [comment]
Hi @blimkemann 
Could it be for this reason that I can use the font icons on iOS in the Iconize's sample, but not in my own project?

**Comment by blimkemann** [comment]
Probably not. My guess is that in your iOS project you have not included the font in your manifest. I believe there is documentation about that in the readme…

**Comment by Goldstrike** [comment]
There is no longer reference to the **manifest** in the **readme**, only the add of tue used fonts in **Info.plist**:
I've created  a sample based on the basic project that is created when one start a new Xamarin.Forms project: [BottomTp](https://github.com/Goldstrike/BottomTp). On Android, the font icons are well displayed, but there are not displayed on iOS.

**Comment by Goldstrike** [comment]
Finally, the problem was solved by adding the 2 used Fonts in the "Resources" folder. So it could be interesting to fix this in the next package too.

**Comment by Im-PJ** [comment]
Pleaseeee update the nuget package...
