### ISSUE TITLE
IconTabbedPage: Docs or samples does not show clearly how to add icons to tabs

### ISSUE THREAD

**Issue by Kode4Hue** [jsmarcus/Iconize#76]
I have been trying to get this to work some time.

I have looked at the docs but the example provided does not show how to set each tab to a specify font icon. e.g. Home tab -> fas-home icon.

**Comment by lewcianci** [comment]
This is my TabbedPage XAML.

`<iconize:IconTabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
            xmlns:local="clr-namespace:MapManPrism.Views"
                        xmlns:behaviors="clr-namespace:Prism.Behaviors;assembly=Prism.Forms"
                xmlns:iconize="clr-namespace:Plugin.Iconize;assembly=Plugin.Iconize"
            prism:ViewModelLocator.AutowireViewModel="True"
            x:Class="MapManPrism.Views.MainTabbedPage" Title="{Binding Title}">
    <iconize:IconNavigationPage Title="Home" Icon="fas-home">
        <x:Arguments>
            <local:HomePage></local:HomePage>
        </x:Arguments>
    </iconize:IconNavigationPage>
    <iconize:IconNavigationPage Title="Maps" Icon="fas-map">
        <x:Arguments>
            <local:MapsPage></local:MapsPage>
        </x:Arguments>
    </iconize:IconNavigationPage>
    <iconize:IconNavigationPage Title="Carts" Icon="fas-shopping-cart">
        <x:Arguments>
            <local:CartsPage></local:CartsPage>
        </x:Arguments>
    </iconize:IconNavigationPage>
    <iconize:IconNavigationPage Title="Settings" Icon="fas-sliders-h">
        <x:Arguments>
            <local:SettingsPage></local:SettingsPage>
        </x:Arguments>
    </iconize:IconNavigationPage>
</iconize:IconTabbedPage>`

Key takeaways:
- You have to use the IconTabbedPage
- Reference font awesome to know the font names
