### ISSUE TITLE
Extensibility, I'd like to add newer version of FontAwesome

### ISSUE THREAD

**Issue by Robotuner** [jsmarcus/Iconize#78]
Marcus:  I am hoping that you can take a couple of minutes to look at what my attempt to append to the Iconize.Fonts that are available in my xamarin forms project.  I am currently using Iconize.Fonts.FontAwesome v 1.0.10

I would like to take advantage of the plane-arrival and plane-departure fontAwesome icons in version 5.1 so I thought I would follow your lead (Extensibility) on adding a new font.  I have

1.  Create a static class 
    public static class AvnFontAwesomeCollection
    {
        public static IList<IIcon> Icons { get; } = new List<IIcon>();

        static AvmFontAwesomeCollection()
        {
            new Icon("avn-plane-arrival", '\uf5af');
            new Icon("avn-plane-departure", '\uf5b0');
        }
    }
2.  Created a class that implements IconModule
    public class AvnFontAwesome : IconModule
    {
        public AvnFontAwesome() :
            base("AvnFontAwesome", "AvnFontAwesome", "FontAwesome5FreeSolid900.otf", AvnFontAwesomeCollection.Icons) { }
 
    }	
3.  Added "With"statement in AppDelegate:

		public override bool FinishedLaunching(UIApplication app, NSDictionary options)
		{
            try
            {
                Plugin.Iconize.Iconize.With(new Plugin.Iconize.Fonts.FontAwesomeModule())
                    .With(new Avianis.App.Resources.AvnFontAwesome());    
			}					
		}
		
4. and added to my info.plist:
	<key>UIAppFonts</key>
	<array>
		<string>Fonts/iconize-fontawesome.ttf</string>
    <string>Fonts/FontAwesome5FreeSolid900.otf</string>
	</array>
	
5.  In my Xaml, I am attempting to :
	<iconize:IconButton Text="avn-plane-departure" Style="{StaticResource expenseStyle}"                            
			Clicked="OnDepartureExpenseClicked">
		<Button.Triggers>
			<DataTrigger TargetType="Button" Binding="{Binding IsFlightLegDepartureExpense}" Value="true">
				<Setter Property="BackgroundColor" Value="{StaticResource ButtonSuccessColor}" />
				<Setter Property="BorderColor" Value="Black" />
			</DataTrigger>
		</Button.Triggers>
	</iconize:IconButton>
	
but with no success.  I can substitute avn-plane-departure with something from the fontAwesome collection (fa-camera)and it will work.	
Is there something obvious that I am missing?

Thanks

**Comment by EndlessDelirium** [comment]
I've added a pull request that updates the plugin to font awesome 5.3.1. The plane-departure and all other more recently added icons should just work when you use this. See #80
