### ISSUE TITLE
Update Ionicons

### ISSUE THREAD

**Issue by flobaader** [jsmarcus/Iconize#79]
Hello,

I just found your project and so far it looks really cool.

I wanted to ask you if its possible to update Ionicons to the recent version 5.0 (currently 2.0.1).
There have been lots of changes and the old icons look very different from the updated ones.

Kind regards,
Florian

**Comment by jsmarcus** [comment]
Ionicons 3+ does not supply a font file so it cannot be updated. They have switched to only svg.
