### ISSUE TITLE
IconToolbarItem.IsVisible does not work anymore after 3.2.0.74 update

### ISSUE THREAD

**Issue by lightwalker01** [jsmarcus/Iconize#82]
Setting IconToolbarItem.IsVisible (in XAML) to false, the element is still visible.
It works works up to and including version 3.0.0.73

**Comment by 640774n6** [comment]
I am experiencing this issue as well, but only in my Android project. My iOS project is respecting the IconToolbarItem.IsVisible property.

Xamarin.Forms (3.2.0.839982)
Xam.Plugin.Iconize (3.2.0.74)

**Comment by lightwalker01** [comment]
> I am experiencing this issue as well, but only in my Android project. My iOS project is respecting the IconToolbarItem.IsVisible property.
> 

Yes, in the android project for me too. I do not have the iOS project to try.

**Comment by 640774n6** [comment]
This is no longer an issue for me on 3.2.0.75

**Comment by jsmarcus** [comment]
Fix released with 3.2.0.75
