### ISSUE TITLE
FontAwesome icons randomly change sizes when used in an IconTabbedPage (Android)

### ISSUE THREAD

**Issue by vaindil** [jsmarcus/Iconize#89]
In the gif below I have an IconTabbedPage with a few FontAwesome icons. The sizes of all four of the icons fluctuate whenever any movement occurs. The first two only change a tiny amount, but if you look closely you can see that they are changing.

Versions:
* Xamarin.Forms: 3.2.0.871581
* Xam.Plugin.Iconize: 3.2.0.77
* Xam.Plugin.Iconize.FontAwesome: 3.2.0.77
* All Xamarin.Android libraries: 27.0.2.1

![broken tabs](https://user-images.githubusercontent.com/771134/46491937-2574a700-c7da-11e8-90b0-4f20b6c20785.gif)

**Comment by 640774n6** [comment]
Was able to reproduce this and found the problem. Submitted PR.

**Comment by 640774n6** [comment]
Fixed for me in 3.3.0.85. @vaindil are you able to verify on your end?

**Comment by jsmarcus** [comment]
@vaindil can you verify this is fixed for you?

**Comment by vaindil** [comment]
Just upgraded to the latest version (3.3.0.90) and the problem is resolved. Thank you!
