### ISSUE TITLE
Brands Icons on FontAwesomePro

### ISSUE THREAD

**Issue by chrisfoulds** [jsmarcus/Iconize#94]
I am using the FontAwesome Pro module and it works great however there is no support for brand icons.
So I thought I would add the standard Fontawesome module to get them but then my project bloats out with additional ttf files etc. that I don't need for the other parts of Fontawesome.

Is it possible for you to add the brands module to Fontawesome Pro Module ?

Thanks

**Comment by chrisfoulds** [comment]
For now I just put this in place.
`using System.Collections.Generic;

namespace Plugin.Iconize.Fonts
{
    /// <summary>
    /// Defines the <see cref="FontAwesomeProBrandsModule" /> icon module.
    /// </summary>
    /// <seealso cref="Plugin.Iconize.IconModule" />
    public sealed class FontAwesomeProBrandsModule : IconModule
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FontAwesomeProBrandsModule" /> class.
        /// </summary>
        public FontAwesomeProBrandsModule()
            : base("Font Awesome 5 Pro Brands", "FontAwesome5ProBrands", "iconize-fontawesome-pro-brands.ttf", FontAwesomeProCollectionExtension.BrandIcons)
        {
            // Intentionally left blank
        }
    }

    /// <summary>
    /// Defines the <see cref="FontAwesomeProCollection" /> icon collection.
    /// </summary>
    public static class FontAwesomeProCollectionExtension
    {
        /// <summary>
        /// Gets the BrandIcons.
        /// </summary>
        /// <value>The BrandIcons.</value>
        public static IList<IIcon> BrandIcons { get; } = new List<IIcon>();

        /// <summary>
        /// Initializes the <see cref="FontAwesomeProCollectionExtension" /> class.
        /// </summary>
        static FontAwesomeProCollectionExtension()
        {
            #region Brands

            BrandIcons.Add("fab-500px", '\uf26e');
            BrandIcons.Add("fab-accessible-icon", '\uf368');
            BrandIcons.Add("fab-accusoft", '\uf369');
            BrandIcons.Add("fab-adn", '\uf170');
            BrandIcons.Add("fab-adversal", '\uf36a');
            BrandIcons.Add("fab-affiliatetheme", '\uf36b');
            BrandIcons.Add("fab-algolia", '\uf36c');
            BrandIcons.Add("fab-alipay", '\uf642');
            BrandIcons.Add("fab-amazon", '\uf270');
            BrandIcons.Add("fab-amazon-pay", '\uf42c');
            BrandIcons.Add("fab-amilia", '\uf36d');
            BrandIcons.Add("fab-android", '\uf17b');
            BrandIcons.Add("fab-angellist", '\uf209');
            BrandIcons.Add("fab-angrycreative", '\uf36e');
            BrandIcons.Add("fab-angular", '\uf420');
            BrandIcons.Add("fab-app-store", '\uf36f');
            BrandIcons.Add("fab-app-store-ios", '\uf370');
            BrandIcons.Add("fab-apper", '\uf371');
            BrandIcons.Add("fab-apple", '\uf179');
            BrandIcons.Add("fab-apple-pay", '\uf415');
            BrandIcons.Add("fab-asymmetrik", '\uf372');
            BrandIcons.Add("fab-audible", '\uf373');
            BrandIcons.Add("fab-autoprefixer", '\uf41c');
            BrandIcons.Add("fab-avianex", '\uf374');
            BrandIcons.Add("fab-aviato", '\uf421');
            BrandIcons.Add("fab-aws", '\uf375');
            BrandIcons.Add("fab-bandcamp", '\uf2d5');
            BrandIcons.Add("fab-behance", '\uf1b4');
            BrandIcons.Add("fab-behance-square", '\uf1b5');
            BrandIcons.Add("fab-bimobject", '\uf378');
            BrandIcons.Add("fab-bitbucket", '\uf171');
            BrandIcons.Add("fab-bitcoin", '\uf379');
            BrandIcons.Add("fab-bity", '\uf37a');
            BrandIcons.Add("fab-black-tie", '\uf27e');
            BrandIcons.Add("fab-blackberry", '\uf37b');
            BrandIcons.Add("fab-blogger", '\uf37c');
            BrandIcons.Add("fab-blogger-b", '\uf37d');
            BrandIcons.Add("fab-bluetooth", '\uf293');
            BrandIcons.Add("fab-bluetooth-b", '\uf294');
            BrandIcons.Add("fab-btc", '\uf15a');
            BrandIcons.Add("fab-buromobelexperte", '\uf37f');
            BrandIcons.Add("fab-buysellads", '\uf20d');
            BrandIcons.Add("fab-cc-amazon-pay", '\uf42d');
            BrandIcons.Add("fab-cc-amex", '\uf1f3');
            BrandIcons.Add("fab-cc-apple-pay", '\uf416');
            BrandIcons.Add("fab-cc-diners-club", '\uf24c');
            BrandIcons.Add("fab-cc-discover", '\uf1f2');
            BrandIcons.Add("fab-cc-jcb", '\uf24b');
            BrandIcons.Add("fab-cc-mastercard", '\uf1f1');
            BrandIcons.Add("fab-cc-paypal", '\uf1f4');
            BrandIcons.Add("fab-cc-stripe", '\uf1f5');
            BrandIcons.Add("fab-cc-visa", '\uf1f0');
            BrandIcons.Add("fab-centercode", '\uf380');
            BrandIcons.Add("fab-chrome", '\uf268');
            BrandIcons.Add("fab-cloudscale", '\uf383');
            BrandIcons.Add("fab-cloudsmith", '\uf384');
            BrandIcons.Add("fab-cloudversify", '\uf385');
            BrandIcons.Add("fab-codepen", '\uf1cb');
            BrandIcons.Add("fab-codiepie", '\uf284');
            BrandIcons.Add("fab-connectdevelop", '\uf20e');
            BrandIcons.Add("fab-contao", '\uf26d');
            BrandIcons.Add("fab-cpanel", '\uf388');
            BrandIcons.Add("fab-creative-commons", '\uf25e');
            BrandIcons.Add("fab-creative-commons-by", '\uf4e7');
            BrandIcons.Add("fab-creative-commons-nc", '\uf4e8');
            BrandIcons.Add("fab-creative-commons-nc-eu", '\uf4e9');
            BrandIcons.Add("fab-creative-commons-nc-jp", '\uf4ea');
            BrandIcons.Add("fab-creative-commons-nd", '\uf4eb');
            BrandIcons.Add("fab-creative-commons-pd", '\uf4ec');
            BrandIcons.Add("fab-creative-commons-pd-alt", '\uf4ed');
            BrandIcons.Add("fab-creative-commons-remix", '\uf4ee');
            BrandIcons.Add("fab-creative-commons-sa", '\uf4ef');
            BrandIcons.Add("fab-creative-commons-sampling", '\uf4f0');
            BrandIcons.Add("fab-creative-commons-sampling-plus", '\uf4f1');
            BrandIcons.Add("fab-creative-commons-share", '\uf4f2');
            BrandIcons.Add("fab-css3", '\uf13c');
            BrandIcons.Add("fab-css3-alt", '\uf38b');
            BrandIcons.Add("fab-cuttlefish", '\uf38c');
            BrandIcons.Add("fab-d-and-d", '\uf38d');
            BrandIcons.Add("fab-dashcube", '\uf210');
            BrandIcons.Add("fab-delicious", '\uf1a5');
            BrandIcons.Add("fab-deploydog", '\uf38e');
            BrandIcons.Add("fab-deskpro", '\uf38f');
            BrandIcons.Add("fab-deviantart", '\uf1bd');
            BrandIcons.Add("fab-digg", '\uf1a6');
            BrandIcons.Add("fab-digital-ocean", '\uf391');
            BrandIcons.Add("fab-discord", '\uf392');
            BrandIcons.Add("fab-discourse", '\uf393');
            BrandIcons.Add("fab-dochub", '\uf394');
            BrandIcons.Add("fab-docker", '\uf395');
            BrandIcons.Add("fab-draft2digital", '\uf396');
            BrandIcons.Add("fab-dribbble", '\uf17d');
            BrandIcons.Add("fab-dribbble-square", '\uf397');
            BrandIcons.Add("fab-dropbox", '\uf16b');
            BrandIcons.Add("fab-drupal", '\uf1a9');
            BrandIcons.Add("fab-dyalog", '\uf399');
            BrandIcons.Add("fab-earlybirds", '\uf39a');
            BrandIcons.Add("fab-ebay", '\uf4f4');
            BrandIcons.Add("fab-edge", '\uf282');
            BrandIcons.Add("fab-elementor", '\uf430');
            BrandIcons.Add("fab-ello", '\uf5f1');
            BrandIcons.Add("fab-ember", '\uf423');
            BrandIcons.Add("fab-empire", '\uf1d1');
            BrandIcons.Add("fab-envira", '\uf299');
            BrandIcons.Add("fab-erlang", '\uf39d');
            BrandIcons.Add("fab-ethereum", '\uf42e');
            BrandIcons.Add("fab-etsy", '\uf2d7');
            BrandIcons.Add("fab-expeditedssl", '\uf23e');
            BrandIcons.Add("fab-facebook", '\uf09a');
            BrandIcons.Add("fab-facebook-f", '\uf39e');
            BrandIcons.Add("fab-facebook-messenger", '\uf39f');
            BrandIcons.Add("fab-facebook-square", '\uf082');
            BrandIcons.Add("fab-firefox", '\uf269');
            BrandIcons.Add("fab-first-order", '\uf2b0');
            BrandIcons.Add("fab-first-order-alt", '\uf50a');
            BrandIcons.Add("fab-firstdraft", '\uf3a1');
            BrandIcons.Add("fab-flickr", '\uf16e');
            BrandIcons.Add("fab-flipboard", '\uf44d');
            BrandIcons.Add("fab-fly", '\uf417');
            BrandIcons.Add("fab-font-awesome", '\uf2b4');
            BrandIcons.Add("fab-font-awesome-alt", '\uf35c');
            BrandIcons.Add("fab-font-awesome-flag", '\uf425');
            BrandIcons.Add("fab-font-awesome-logo-full", '\uf4e6');
            BrandIcons.Add("fab-fonticons", '\uf280');
            BrandIcons.Add("fab-fonticons-fi", '\uf3a2');
            BrandIcons.Add("fab-fort-awesome", '\uf286');
            BrandIcons.Add("fab-fort-awesome-alt", '\uf3a3');
            BrandIcons.Add("fab-forumbee", '\uf211');
            BrandIcons.Add("fab-foursquare", '\uf180');
            BrandIcons.Add("fab-free-code-camp", '\uf2c5');
            BrandIcons.Add("fab-freebsd", '\uf3a4');
            BrandIcons.Add("fab-fulcrum", '\uf50b');
            BrandIcons.Add("fab-galactic-republic", '\uf50c');
            BrandIcons.Add("fab-galactic-senate", '\uf50d');
            BrandIcons.Add("fab-get-pocket", '\uf265');
            BrandIcons.Add("fab-gg", '\uf260');
            BrandIcons.Add("fab-gg-circle", '\uf261');
            BrandIcons.Add("fab-git", '\uf1d3');
            BrandIcons.Add("fab-git-square", '\uf1d2');
            BrandIcons.Add("fab-github", '\uf09b');
            BrandIcons.Add("fab-github-alt", '\uf113');
            BrandIcons.Add("fab-github-square", '\uf092');
            BrandIcons.Add("fab-gitkraken", '\uf3a6');
            BrandIcons.Add("fab-gitlab", '\uf296');
            BrandIcons.Add("fab-gitter", '\uf426');
            BrandIcons.Add("fab-glide", '\uf2a5');
            BrandIcons.Add("fab-glide-g", '\uf2a6');
            BrandIcons.Add("fab-gofore", '\uf3a7');
            BrandIcons.Add("fab-goodreads", '\uf3a8');
            BrandIcons.Add("fab-goodreads-g", '\uf3a9');
            BrandIcons.Add("fab-google", '\uf1a0');
            BrandIcons.Add("fab-google-drive", '\uf3aa');
            BrandIcons.Add("fab-google-play", '\uf3ab');
            BrandIcons.Add("fab-google-plus", '\uf2b3');
            BrandIcons.Add("fab-google-plus-g", '\uf0d5');
            BrandIcons.Add("fab-google-plus-square", '\uf0d4');
            BrandIcons.Add("fab-google-wallet", '\uf1ee');
            BrandIcons.Add("fab-gratipay", '\uf184');
            BrandIcons.Add("fab-grav", '\uf2d6');
            BrandIcons.Add("fab-gripfire", '\uf3ac');
            BrandIcons.Add("fab-grunt", '\uf3ad');
            BrandIcons.Add("fab-gulp", '\uf3ae');
            BrandIcons.Add("fab-hacker-news", '\uf1d4');
            BrandIcons.Add("fab-hacker-news-square", '\uf3af');
            BrandIcons.Add("fab-hackerrank", '\uf5f7');
            BrandIcons.Add("fab-hips", '\uf452');
            BrandIcons.Add("fab-hire-a-helper", '\uf3b0');
            BrandIcons.Add("fab-hooli", '\uf427');
            BrandIcons.Add("fab-hornbill", '\uf592');
            BrandIcons.Add("fab-hotjar", '\uf3b1');
            BrandIcons.Add("fab-houzz", '\uf27c');
            BrandIcons.Add("fab-html5", '\uf13b');
            BrandIcons.Add("fab-hubspot", '\uf3b2');
            BrandIcons.Add("fab-imdb", '\uf2d8');
            BrandIcons.Add("fab-instagram", '\uf16d');
            BrandIcons.Add("fab-internet-explorer", '\uf26b');
            BrandIcons.Add("fab-ioxhost", '\uf208');
            BrandIcons.Add("fab-itunes", '\uf3b4');
            BrandIcons.Add("fab-itunes-note", '\uf3b5');
            BrandIcons.Add("fab-java", '\uf4e4');
            BrandIcons.Add("fab-jedi-order", '\uf50e');
            BrandIcons.Add("fab-jenkins", '\uf3b6');
            BrandIcons.Add("fab-joget", '\uf3b7');
            BrandIcons.Add("fab-joomla", '\uf1aa');
            BrandIcons.Add("fab-js", '\uf3b8');
            BrandIcons.Add("fab-js-square", '\uf3b9');
            BrandIcons.Add("fab-jsfiddle", '\uf1cc');
            BrandIcons.Add("fab-kaggle", '\uf5fa');
            BrandIcons.Add("fab-keybase", '\uf4f5');
            BrandIcons.Add("fab-keycdn", '\uf3ba');
            BrandIcons.Add("fab-kickstarter", '\uf3bb');
            BrandIcons.Add("fab-kickstarter-k", '\uf3bc');
            BrandIcons.Add("fab-korvue", '\uf42f');
            BrandIcons.Add("fab-laravel", '\uf3bd');
            BrandIcons.Add("fab-lastfm", '\uf202');
            BrandIcons.Add("fab-lastfm-square", '\uf203');
            BrandIcons.Add("fab-leanpub", '\uf212');
            BrandIcons.Add("fab-less", '\uf41d');
            BrandIcons.Add("fab-line", '\uf3c0');
            BrandIcons.Add("fab-linkedin", '\uf08c');
            BrandIcons.Add("fab-linkedin-in", '\uf0e1');
            BrandIcons.Add("fab-linode", '\uf2b8');
            BrandIcons.Add("fab-linux", '\uf17c');
            BrandIcons.Add("fab-lyft", '\uf3c3');
            BrandIcons.Add("fab-magento", '\uf3c4');
            BrandIcons.Add("fab-mailchimp", '\uf59e');
            BrandIcons.Add("fab-mandalorian", '\uf50f');
            BrandIcons.Add("fab-markdown", '\uf60f');
            BrandIcons.Add("fab-mastodon", '\uf4f6');
            BrandIcons.Add("fab-maxcdn", '\uf136');
            BrandIcons.Add("fab-medapps", '\uf3c6');
            BrandIcons.Add("fab-medium", '\uf23a');
            BrandIcons.Add("fab-medium-m", '\uf3c7');
            BrandIcons.Add("fab-medrt", '\uf3c8');
            BrandIcons.Add("fab-meetup", '\uf2e0');
            BrandIcons.Add("fab-megaport", '\uf5a3');
            BrandIcons.Add("fab-microsoft", '\uf3ca');
            BrandIcons.Add("fab-mix", '\uf3cb');
            BrandIcons.Add("fab-mixcloud", '\uf289');
            BrandIcons.Add("fab-mizuni", '\uf3cc');
            BrandIcons.Add("fab-modx", '\uf285');
            BrandIcons.Add("fab-monero", '\uf3d0');
            BrandIcons.Add("fab-napster", '\uf3d2');
            BrandIcons.Add("fab-neos", '\uf612');
            BrandIcons.Add("fab-nimblr", '\uf5a8');
            BrandIcons.Add("fab-nintendo-switch", '\uf418');
            BrandIcons.Add("fab-node", '\uf419');
            BrandIcons.Add("fab-node-js", '\uf3d3');
            BrandIcons.Add("fab-npm", '\uf3d4');
            BrandIcons.Add("fab-ns8", '\uf3d5');
            BrandIcons.Add("fab-nutritionix", '\uf3d6');
            BrandIcons.Add("fab-odnoklassniki", '\uf263');
            BrandIcons.Add("fab-odnoklassniki-square", '\uf264');
            BrandIcons.Add("fab-old-republic", '\uf510');
            BrandIcons.Add("fab-opencart", '\uf23d');
            BrandIcons.Add("fab-openid", '\uf19b');
            BrandIcons.Add("fab-opera", '\uf26a');
            BrandIcons.Add("fab-optin-monster", '\uf23c');
            BrandIcons.Add("fab-osi", '\uf41a');
            BrandIcons.Add("fab-page4", '\uf3d7');
            BrandIcons.Add("fab-pagelines", '\uf18c');
            BrandIcons.Add("fab-palfed", '\uf3d8');
            BrandIcons.Add("fab-patreon", '\uf3d9');
            BrandIcons.Add("fab-paypal", '\uf1ed');
            BrandIcons.Add("fab-periscope", '\uf3da');
            BrandIcons.Add("fab-phabricator", '\uf3db');
            BrandIcons.Add("fab-phoenix-framework", '\uf3dc');
            BrandIcons.Add("fab-phoenix-squadron", '\uf511');
            BrandIcons.Add("fab-php", '\uf457');
            BrandIcons.Add("fab-pied-piper", '\uf2ae');
            BrandIcons.Add("fab-pied-piper-alt", '\uf1a8');
            BrandIcons.Add("fab-pied-piper-hat", '\uf4e5');
            BrandIcons.Add("fab-pied-piper-pp", '\uf1a7');
            BrandIcons.Add("fab-pinterest", '\uf0d2');
            BrandIcons.Add("fab-pinterest-p", '\uf231');
            BrandIcons.Add("fab-pinterest-square", '\uf0d3');
            BrandIcons.Add("fab-playstation", '\uf3df');
            BrandIcons.Add("fab-product-hunt", '\uf288');
            BrandIcons.Add("fab-pushed", '\uf3e1');
            BrandIcons.Add("fab-python", '\uf3e2');
            BrandIcons.Add("fab-qq", '\uf1d6');
            BrandIcons.Add("fab-quinscape", '\uf459');
            BrandIcons.Add("fab-quora", '\uf2c4');
            BrandIcons.Add("fab-r-project", '\uf4f7');
            BrandIcons.Add("fab-ravelry", '\uf2d9');
            BrandIcons.Add("fab-react", '\uf41b');
            BrandIcons.Add("fab-readme", '\uf4d5');
            BrandIcons.Add("fab-rebel", '\uf1d0');
            BrandIcons.Add("fab-red-river", '\uf3e3');
            BrandIcons.Add("fab-reddit", '\uf1a1');
            BrandIcons.Add("fab-reddit-alien", '\uf281');
            BrandIcons.Add("fab-reddit-square", '\uf1a2');
            BrandIcons.Add("fab-rendact", '\uf3e4');
            BrandIcons.Add("fab-renren", '\uf18b');
            BrandIcons.Add("fab-replyd", '\uf3e6');
            BrandIcons.Add("fab-researchgate", '\uf4f8');
            BrandIcons.Add("fab-resolving", '\uf3e7');
            BrandIcons.Add("fab-rev", '\uf5b2');
            BrandIcons.Add("fab-rocketchat", '\uf3e8');
            BrandIcons.Add("fab-rockrms", '\uf3e9');
            BrandIcons.Add("fab-safari", '\uf267');
            BrandIcons.Add("fab-sass", '\uf41e');
            BrandIcons.Add("fab-schlix", '\uf3ea');
            BrandIcons.Add("fab-scribd", '\uf28a');
            BrandIcons.Add("fab-searchengin", '\uf3eb');
            BrandIcons.Add("fab-sellcast", '\uf2da');
            BrandIcons.Add("fab-sellsy", '\uf213');
            BrandIcons.Add("fab-servicestack", '\uf3ec');
            BrandIcons.Add("fab-shirtsinbulk", '\uf214');
            BrandIcons.Add("fab-shopware", '\uf5b5');
            BrandIcons.Add("fab-simplybuilt", '\uf215');
            BrandIcons.Add("fab-sistrix", '\uf3ee');
            BrandIcons.Add("fab-sith", '\uf512');
            BrandIcons.Add("fab-skyatlas", '\uf216');
            BrandIcons.Add("fab-skype", '\uf17e');
            BrandIcons.Add("fab-slack", '\uf198');
            BrandIcons.Add("fab-slack-hash", '\uf3ef');
            BrandIcons.Add("fab-slideshare", '\uf1e7');
            BrandIcons.Add("fab-snapchat", '\uf2ab');
            BrandIcons.Add("fab-snapchat-ghost", '\uf2ac');
            BrandIcons.Add("fab-snapchat-square", '\uf2ad');
            BrandIcons.Add("fab-soundcloud", '\uf1be');
            BrandIcons.Add("fab-speakap", '\uf3f3');
            BrandIcons.Add("fab-spotify", '\uf1bc');
            BrandIcons.Add("fab-squarespace", '\uf5be');
            BrandIcons.Add("fab-stack-exchange", '\uf18d');
            BrandIcons.Add("fab-stack-overflow", '\uf16c');
            BrandIcons.Add("fab-staylinked", '\uf3f5');
            BrandIcons.Add("fab-steam", '\uf1b6');
            BrandIcons.Add("fab-steam-square", '\uf1b7');
            BrandIcons.Add("fab-steam-symbol", '\uf3f6');
            BrandIcons.Add("fab-sticker-mule", '\uf3f7');
            BrandIcons.Add("fab-strava", '\uf428');
            BrandIcons.Add("fab-stripe", '\uf429');
            BrandIcons.Add("fab-stripe-s", '\uf42a');
            BrandIcons.Add("fab-studiovinari", '\uf3f8');
            BrandIcons.Add("fab-stumbleupon", '\uf1a4');
            BrandIcons.Add("fab-stumbleupon-circle", '\uf1a3');
            BrandIcons.Add("fab-superpowers", '\uf2dd');
            BrandIcons.Add("fab-supple", '\uf3f9');
            BrandIcons.Add("fab-teamspeak", '\uf4f9');
            BrandIcons.Add("fab-telegram", '\uf2c6');
            BrandIcons.Add("fab-telegram-plane", '\uf3fe');
            BrandIcons.Add("fab-tencent-weibo", '\uf1d5');
            BrandIcons.Add("fab-the-red-yeti", '\uf69d');
            BrandIcons.Add("fab-themeco", '\uf5c6');
            BrandIcons.Add("fab-themeisle", '\uf2b2');
            BrandIcons.Add("fab-trade-federation", '\uf513');
            BrandIcons.Add("fab-trello", '\uf181');
            BrandIcons.Add("fab-tripadvisor", '\uf262');
            BrandIcons.Add("fab-tumblr", '\uf173');
            BrandIcons.Add("fab-tumblr-square", '\uf174');
            BrandIcons.Add("fab-twitch", '\uf1e8');
            BrandIcons.Add("fab-twitter", '\uf099');
            BrandIcons.Add("fab-twitter-square", '\uf081');
            BrandIcons.Add("fab-typo3", '\uf42b');
            BrandIcons.Add("fab-uber", '\uf402');
            BrandIcons.Add("fab-uikit", '\uf403');
            BrandIcons.Add("fab-uniregistry", '\uf404');
            BrandIcons.Add("fab-untappd", '\uf405');
            BrandIcons.Add("fab-usb", '\uf287');
            BrandIcons.Add("fab-ussunnah", '\uf407');
            BrandIcons.Add("fab-vaadin", '\uf408');
            BrandIcons.Add("fab-viacoin", '\uf237');
            BrandIcons.Add("fab-viadeo", '\uf2a9');
            BrandIcons.Add("fab-viadeo-square", '\uf2aa');
            BrandIcons.Add("fab-viber", '\uf409');
            BrandIcons.Add("fab-vimeo", '\uf40a');
            BrandIcons.Add("fab-vimeo-square", '\uf194');
            BrandIcons.Add("fab-vimeo-v", '\uf27d');
            BrandIcons.Add("fab-vine", '\uf1ca');
            BrandIcons.Add("fab-vk", '\uf189');
            BrandIcons.Add("fab-vnv", '\uf40b');
            BrandIcons.Add("fab-vuejs", '\uf41f');
            BrandIcons.Add("fab-weebly", '\uf5cc');
            BrandIcons.Add("fab-weibo", '\uf18a');
            BrandIcons.Add("fab-weixin", '\uf1d7');
            BrandIcons.Add("fab-whatsapp", '\uf232');
            BrandIcons.Add("fab-whatsapp-square", '\uf40c');
            BrandIcons.Add("fab-whmcs", '\uf40d');
            BrandIcons.Add("fab-wikipedia-w", '\uf266');
            BrandIcons.Add("fab-windows", '\uf17a');
            BrandIcons.Add("fab-wix", '\uf5cf');
            BrandIcons.Add("fab-wolf-pack-battalion", '\uf514');
            BrandIcons.Add("fab-wordpress", '\uf19a');
            BrandIcons.Add("fab-wordpress-simple", '\uf411');
            BrandIcons.Add("fab-wpbeginner", '\uf297');
            BrandIcons.Add("fab-wpexplorer", '\uf2de');
            BrandIcons.Add("fab-wpforms", '\uf298');
            BrandIcons.Add("fab-xbox", '\uf412');
            BrandIcons.Add("fab-xing", '\uf168');
            BrandIcons.Add("fab-xing-square", '\uf169');
            BrandIcons.Add("fab-y-combinator", '\uf23b');
            BrandIcons.Add("fab-yahoo", '\uf19e');
            BrandIcons.Add("fab-yandex", '\uf413');
            BrandIcons.Add("fab-yandex-international", '\uf414');
            BrandIcons.Add("fab-yelp", '\uf1e9');
            BrandIcons.Add("fab-yoast", '\uf2b1');
            BrandIcons.Add("fab-youtube", '\uf167');
            BrandIcons.Add("fab-youtube-square", '\uf431');
            BrandIcons.Add("fab-zhihu", '\uf63f');

            #endregion
        }
    }
}`

**Comment by jsmarcus** [comment]
Merged through #100
