### ISSUE TITLE
Can not resolve reference: `Plugin.Iconize.Droid`, referenced by `FormsPlugin.Iconize.Droid`

### ISSUE THREAD

**Issue by husseinmohkhalil** [jsmarcus/Iconize#96]
Create a new project with Xamarin.forms and shared project only for android
add nuget package for 
Xam.Plugin.Iconize 
Xam.FormsPlugin.Iconize -
Xam.Plugin.Iconize.FontAwesome

Compile => Error

Severity	Code	Description	Project	File	Line	Suppression State
Error		Can not resolve reference: `Plugin.Iconize.Droid`, referenced by `FormsPlugin.Iconize.Droid`. Please add a NuGet package or assembly reference for `Plugin.Iconize.Droid`, or remove the reference to `FormsPlugin.Iconize.Droid`.	IconTest.Android

**Comment by jsmarcus** [comment]
Xam.FormsPlugin.Iconize is not used.

**Comment by husseinmohkhalil** [comment]
sorry, but what do you mean by "It is not used"? 
I am following this https://github.com/jsmarcus/Xamarin.Plugins/tree/master/Iconize 
and it says that it is a must to include Xam.FormsPlugin.Iconize

**Comment by jsmarcus** [comment]
You're looking at the wrong project. Funnily enough, you raised your issue in the correct project.

https://github.com/jsmarcus/Iconize/blob/master/README.md

**Comment by albrecht-jun-zhang** [comment]
Thanks @husseinmohkhalil and @jsmarcus, I was looking at the wrong project as well.
